# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

. ~/work/dotfiles/z/z.sh

# aliases
for file in ~/.{zshrc-local,aliases}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# 補完を楽にするやつ
# `cd f/b/b[TAB]`で`cd foooo/barrr/bazzz`と展開
autoload -U compinit && compinit
# `take` command
# Create a new directory and change to it, will create intermediate directories as required.
function take() {
  mkdir -p $1
  cd $1
}

# npm
export PATH=$HOME/n:$PATH
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH

## rbenv setting
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

#重複したpathを一意にする
typeset -U path cdpath fpath manpath

# 環境変数など
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# iterm2 shell integration
# https://iterm2.com/documentation-shell-integration.html
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
iterm2_print_user_vars() {
  t1=''
  gitBranch=$((git branch 2> /dev/null) | grep \* | cut -c3-)
  on=' on '
  gitRepo=$([[ -d .git ]] && basename `git rev-parse --show-toplevel`);
  if ! [ -z ${gitBranch} ]; then
    iterm2_set_user_var git ${t1}${gitRepo}${on}${gitBranch}
  fi
  iterm2_set_user_var ip $(ip)
  iterm2_set_user_var node-v $(node -v)
  iterm2_set_user_var npm-v $(npm -v)
}

alias sudo='nocorrect sudo'

date
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
